trigger: none

name: Deploy VM from snapshot
variables:
  azureServiceConnection: 'DevOps2Azure'
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      snapshotName=$(az snapshot list --query "[?contains(name, 'gaming')].name" -o tsv)
      az deployment group create -g $(resourceGroup) --name deployWebVM --template-file $(templateFilePath) --parameters snapshotName=$(snapshotName) --mode Complete