trigger: none

name: Deploy webVM from snapshot
variables:
  azureServiceConnection: 'DevOps2Azure'
  templateFile: 'webVM/$(templateFileName)'
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az deployment group create -g webVM.rg --name deployWebVM --template-file $(templateFile) --mode Complete